dependencies: ['repositories.bzl', '*/repositories.bzl', 'third_party/**/*']
documentation: ['docs/**/*']
lang-android: ['android/**/*', 'example/android/**/*', 'tools/rulegen/android.go']
lang-cpp: ['cpp/**/*', 'example/cpp/**/*', 'tools/rulegen/cpp.go']
lang-csharp: ['csharp/**/*', 'example/csharp/**/*', 'tools/rulegen/csharp.go']
lang-d: ['d/**/*', 'example/d/**/*', 'tools/rulegen/d.go']
lang-go: ['go/**/*', 'example/go/**/*', 'tools/rulegen/go.go']
lang-grpc-gateway: ['grpc-gateway/**/*', 'example/grpc-gateway/**/*', 'tools/rulegen/grpc_gateway.go']
lang-java: ['java/**/*', 'example/java/**/*', 'tools/rulegen/java.go']
lang-nodejs: ['js/**/*', 'example/js/**/*', 'tools/rulegen/js.go']
lang-objc: ['objc/**/*', 'example/objc/**/*', 'tools/rulegen/objc.go']
lang-php: ['php/**/*', 'example/php/**/*', 'tools/rulegen/php.go']
lang-python: ['python/**/*', 'example/python/**/*', 'tools/rulegen/python.go']
lang-ruby: ['ruby/**/*', 'example/ruby/**/*', 'tools/rulegen/ruby.go']
lang-rust: ['rust/**/*', 'example/rust/**/*', 'tools/rulegen/rust.go']
lang-scala: ['scala/**/*', 'example/scala/**/*', 'tools/rulegen/scala.go']
lang-swift: ['swift/**/*', 'example/swift/**/*', 'tools/rulegen/swift.go']
