lang-android: ['android/*']
lang-closure: ['closure/*']
lang-cpp: ['cpp/*']
lang-csharp: ['csharp/*']
lang-d: ['d/*']
lang-go: ['go/*']
lang-grpc-gateway: ['grpc-gateway/*']
lang-grpc-web: ['grpc-web/*']
lang-java: ['java/*']
lang-nodejs: ['nodejs/*']
lang-objc: ['objc/*']
lang-php: ['php/*']
lang-python: ['python/*']
lang-ruby: ['ruby/*']
lang-rust: ['rust/*']
lang-scala: ['scala/*']
lang-swift: ['swift/*']
