[package]
name = "compile_with_bazel"
version = "0.0.0"

# Mandatory (or Cargo tooling is unhappy)
[lib]
path = "fake_lib.rs"

[dependencies]
futures = "=0.1.28"
grpcio = { version = "=0.4.6", features = [] }
grpcio-compiler = "=0.4.3"
protobuf = { version = "=2.8.1", features = ["with-bytes"] }
protobuf-codegen = "=2.8.1"

log = "=0.4.6" # For routeguide example
serde_json = "*" # For routeguide example

[raze]
genmode = "Remote"
workspace_path = "//rust/raze"
output_buildfile_suffix = "BUILD.bazel"

[raze.crates.protobuf.'2.8.1']
gen_buildrs = true
buildrs_additional_environment_variables = [
    "RUSTC=$$PWD/$(location @rules_proto_grpc//rust/raze:rustc)",
    "CARGO_PKG_VERSION=2.8.1",
]

[raze.crates.protobuf-codegen.'2.8.1']
gen_buildrs = true
extra_aliased_targets = ["cargo_bin_protoc_gen_rust"]

[raze.crates.grpcio.'0.4.6']
gen_buildrs = true

[raze.crates.grpcio-sys.'0.4.7']
gen_buildrs = true
buildrs_additional_environment_variables = [
    "DEBUG=false",
    "HOST=$$TARGET",
    "OPT_LEVEL=3",
    "PROFILE=release",
    "GOCACHE=/tmp/grpcio-sys-gocache",
]

[raze.crates.grpcio-compiler.'0.4.3']
extra_aliased_targets = ["cargo_bin_grpc_rust_plugin"]
